language: java
jdk:
  - oraclejdk8
  - openjdk8
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - MAVEN_OPTS="-Xmx4g"
    - JAVA_OPTS="-Xmx4g"
install:
  - set -e
  - travis_retry sudo apt-get install -y --fix-missing libmagic1 libmagic-dev
  - gem install --no-ri --no-rdoc pdd
  - gem install --no-ri --no-rdoc est
  - gem install --no-ri --no-rdoc xcop
  - mvn install -DskipTests -Dinvoker.skip
  - mvn clean
  - set +e
script:
  - set -e
  - pdd --file=/dev/null --exclude=qulice-maven-plugin/src/it/**/*.java,qulice-checkstyle/src/test/resources/com/qulice/checkstyle/AtClauseOrder.java,qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml,qulice-checkstyle/src/test/resources/**/*
  - est --dir=est --file=/dev/null
  - ./years.sh
  - mvn clean install -Pqulice --errors
  - set +e
